/* Generated by `cargo xtask gen-shim`. DO NOT EDIT.
 *
 * Left column: the value musl bakes into the Rust world at compile
 * time. Right side (taken by the shim as &NAME): cosmo's runtime
 * constant for the same name. Cross-checked at build time by
 * examples/src/bin/shim_tables_check.rs. */
#ifndef RUST_APE_SHIM_TABLES_H_
#define RUST_APE_SHIM_TABLES_H_

/* one-off Linux values the shim logic handles specially */
#if defined(__x86_64__)
#define SHIM_LIN_O_LARGEFILE 32768
#elif defined(__aarch64__)
#define SHIM_LIN_O_LARGEFILE 131072
#endif
#define SHIM_LIN_O_SYNC 1052672
#if defined(__x86_64__)
#define SHIM_LIN_O_DIRECTORY 65536
#elif defined(__aarch64__)
#define SHIM_LIN_O_DIRECTORY 16384
#endif
#if defined(__x86_64__)
#define SHIM_LIN_O_TMPFILE 4259840
#elif defined(__aarch64__)
#define SHIM_LIN_O_TMPFILE 4210688
#endif
#define SHIM_LIN_AT_FDCWD -100
#define SHIM_LIN_AT_SYMLINK_NOFOLLOW 256
#define SHIM_LIN_AT_REMOVEDIR 512
#define SHIM_LIN_AT_SYMLINK_FOLLOW 1024
#define SHIM_LIN_AT_EMPTY_PATH 4096
#define SHIM_LIN_AT_EACCESS 512
#define SHIM_LIN_AT_NO_AUTOMOUNT 2048
#define SHIM_LIN_R_OK 4
#define SHIM_LIN_W_OK 2
#define SHIM_LIN_X_OK 1
#define SHIM_LIN_UTIME_NOW 1073741823
#define SHIM_LIN_UTIME_OMIT 1073741822
#define SHIM_LIN_WNOHANG 1
#define SHIM_LIN_WUNTRACED 2
#define SHIM_LIN_WCONTINUED 8
#define SHIM_LIN_WEXITED 4
#define SHIM_LIN_WSTOPPED 2
#define SHIM_LIN_WNOWAIT 16777216
#if defined(__x86_64__)
#define SHIM_LIN_SYS_waitid 247
#elif defined(__aarch64__)
#define SHIM_LIN_SYS_waitid 95
#endif
#define SHIM_LIN_P_ALL 0
#define SHIM_LIN_P_PID 1
#define SHIM_LIN_P_PGID 2
#define SHIM_LIN_P_PIDFD 3
#define SHIM_LIN_CLD_EXITED 1
#define SHIM_LIN_CLD_KILLED 2
#define SHIM_LIN_CLD_DUMPED 3
#define SHIM_LIN_CLD_TRAPPED 4
#define SHIM_LIN_CLD_STOPPED 5
#define SHIM_LIN_CLD_CONTINUED 6
#define SHIM_LIN_SOCK_CLOEXEC 524288
#define SHIM_LIN_SOCK_NONBLOCK 2048
#define SHIM_LIN_MAP_STACK 131072
#define SHIM_LIN_SIG_BLOCK 0
#define SHIM_LIN_SIG_UNBLOCK 1
#define SHIM_LIN_SIG_SETMASK 2
#define SHIM_LIN_SO_ERROR 4
#define SHIM_LIN_SOL_SOCKET 1
#define SHIM_LIN_IPPROTO_IP 0
#define SHIM_LIN_IPPROTO_TCP 6
#define SHIM_LIN_IPPROTO_IPV6 41
#define SHIM_LIN_IPPROTO_UDP 17
#define SHIM_LIN_F_GETLK 5
#define SHIM_LIN_F_SETLK 6
#define SHIM_LIN_F_SETLKW 7
#define SHIM_LIN_F_SETOWN 8
#define SHIM_LIN_F_GETOWN 9
#define SHIM_LIN_F_DUPFD_CLOEXEC 1030
#define SHIM_LIN_TCGETS 21505
#define SHIM_LIN_TCSETS 21506
#define SHIM_LIN_TCSETSW 21507
#define SHIM_LIN_TCSETSF 21508
#define SHIM_LIN_FIONBIO 21537
#define SHIM_LIN_TCGETS2 -2144578518
#define SHIM_LIN_TCSETS2 1076646955
#define SHIM_LIN_TCSETSW2 1076646956
#define SHIM_LIN_TCSETSF2 1076646957
#define SHIM_LIN_BOTHER 4096
#define SHIM_LIN_CBAUD 4111
#define SHIM_LIN_CBAUDEX 4096
#define SHIM_LIN_TIOCGPGRP 21519
#define SHIM_LIN_TIOCSPGRP 21520
#define SHIM_LIN_TIOCGSID 21545
#if defined(__x86_64__)
#define SHIM_LIN_SYS_futex 202
#elif defined(__aarch64__)
#define SHIM_LIN_SYS_futex 98
#endif
#define SHIM_LIN_FUTEX_WAIT 0
#define SHIM_LIN_FUTEX_WAKE 1
#define SHIM_LIN_FUTEX_PRIVATE_FLAG 128
#define SHIM_LIN_FUTEX_CLOCK_REALTIME 256
#define SHIM_LIN_FUTEX_WAIT_BITSET 9
#define SHIM_LIN_FUTEX_WAKE_BITSET 10
#define SHIM_LIN_FUTEX_BITSET_MATCH_ANY -1
#if defined(__x86_64__)
#define SHIM_LIN_SYS_getrandom 318
#elif defined(__aarch64__)
#define SHIM_LIN_SYS_getrandom 278
#endif

/* SHIM_ERRNO_TABLE <- libc crate; cosmo side declared in libc/errno.h */
#define SHIM_LIN_EPERM 1
static const int SHIM_FIX_EPERM = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOENT 2
static const int SHIM_FIX_ENOENT = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ESRCH 3
static const int SHIM_FIX_ESRCH = 3; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EINTR 4
static const int SHIM_FIX_EINTR = 4; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EIO 5
static const int SHIM_FIX_EIO = 5; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENXIO 6
static const int SHIM_FIX_ENXIO = 6; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_E2BIG 7
static const int SHIM_FIX_E2BIG = 7; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOEXEC 8
static const int SHIM_FIX_ENOEXEC = 8; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EBADF 9
static const int SHIM_FIX_EBADF = 9; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ECHILD 10
static const int SHIM_FIX_ECHILD = 10; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EAGAIN 11
static const int SHIM_FIX_EAGAIN = 11; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOMEM 12
static const int SHIM_FIX_ENOMEM = 12; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EACCES 13
static const int SHIM_FIX_EACCES = 13; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EFAULT 14
static const int SHIM_FIX_EFAULT = 14; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTBLK 15
static const int SHIM_FIX_ENOTBLK = 15; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EBUSY 16
static const int SHIM_FIX_EBUSY = 16; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EEXIST 17
static const int SHIM_FIX_EEXIST = 17; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EXDEV 18
static const int SHIM_FIX_EXDEV = 18; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENODEV 19
static const int SHIM_FIX_ENODEV = 19; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTDIR 20
static const int SHIM_FIX_ENOTDIR = 20; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EISDIR 21
static const int SHIM_FIX_EISDIR = 21; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EINVAL 22
static const int SHIM_FIX_EINVAL = 22; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENFILE 23
static const int SHIM_FIX_ENFILE = 23; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EMFILE 24
static const int SHIM_FIX_EMFILE = 24; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTTY 25
static const int SHIM_FIX_ENOTTY = 25; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ETXTBSY 26
static const int SHIM_FIX_ETXTBSY = 26; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EFBIG 27
static const int SHIM_FIX_EFBIG = 27; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOSPC 28
static const int SHIM_FIX_ENOSPC = 28; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ESPIPE 29
static const int SHIM_FIX_ESPIPE = 29; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EROFS 30
static const int SHIM_FIX_EROFS = 30; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EMLINK 31
static const int SHIM_FIX_EMLINK = 31; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EPIPE 32
static const int SHIM_FIX_EPIPE = 32; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EDOM 33
static const int SHIM_FIX_EDOM = 33; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ERANGE 34
static const int SHIM_FIX_ERANGE = 34; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EDEADLK 35
static const int SHIM_FIX_EDEADLK = 35; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENAMETOOLONG 36
static const int SHIM_FIX_ENAMETOOLONG = 36; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOLCK 37
static const int SHIM_FIX_ENOLCK = 37; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOSYS 38
static const int SHIM_FIX_ENOSYS = 38; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTEMPTY 39
static const int SHIM_FIX_ENOTEMPTY = 39; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ELOOP 40
static const int SHIM_FIX_ELOOP = 40; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOMSG 42
static const int SHIM_FIX_ENOMSG = 42; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EIDRM 43
static const int SHIM_FIX_EIDRM = 43; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOSTR 60
static const int SHIM_FIX_ENOSTR = 60; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENODATA 61
static const int SHIM_FIX_ENODATA = 61; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOSR 63
static const int SHIM_FIX_ENOSR = 63; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENONET 64
static const int SHIM_FIX_ENONET = 64; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EREMOTE 66
static const int SHIM_FIX_EREMOTE = 66; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOLINK 67
static const int SHIM_FIX_ENOLINK = 67; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EPROTO 71
static const int SHIM_FIX_EPROTO = 71; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EMULTIHOP 72
static const int SHIM_FIX_EMULTIHOP = 72; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EBADMSG 74
static const int SHIM_FIX_EBADMSG = 74; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EOVERFLOW 75
static const int SHIM_FIX_EOVERFLOW = 75; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EBADFD 77
static const int SHIM_FIX_EBADFD = 77; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EILSEQ 84
static const int SHIM_FIX_EILSEQ = 84; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ERESTART 85
static const int SHIM_FIX_ERESTART = 85; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EUSERS 87
static const int SHIM_FIX_EUSERS = 87; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTSOCK 88
static const int SHIM_FIX_ENOTSOCK = 88; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EDESTADDRREQ 89
static const int SHIM_FIX_EDESTADDRREQ = 89; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EMSGSIZE 90
static const int SHIM_FIX_EMSGSIZE = 90; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EPROTOTYPE 91
static const int SHIM_FIX_EPROTOTYPE = 91; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOPROTOOPT 92
static const int SHIM_FIX_ENOPROTOOPT = 92; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EPROTONOSUPPORT 93
static const int SHIM_FIX_EPROTONOSUPPORT = 93; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ESOCKTNOSUPPORT 94
static const int SHIM_FIX_ESOCKTNOSUPPORT = 94; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EOPNOTSUPP 95
static const int SHIM_FIX_EOPNOTSUPP = 95; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTSUP 95
static const int SHIM_FIX_ENOTSUP = 95; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EPFNOSUPPORT 96
static const int SHIM_FIX_EPFNOSUPPORT = 96; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EAFNOSUPPORT 97
static const int SHIM_FIX_EAFNOSUPPORT = 97; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EADDRINUSE 98
static const int SHIM_FIX_EADDRINUSE = 98; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EADDRNOTAVAIL 99
static const int SHIM_FIX_EADDRNOTAVAIL = 99; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENETDOWN 100
static const int SHIM_FIX_ENETDOWN = 100; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENETUNREACH 101
static const int SHIM_FIX_ENETUNREACH = 101; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENETRESET 102
static const int SHIM_FIX_ENETRESET = 102; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ECONNABORTED 103
static const int SHIM_FIX_ECONNABORTED = 103; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ECONNRESET 104
static const int SHIM_FIX_ECONNRESET = 104; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOBUFS 105
static const int SHIM_FIX_ENOBUFS = 105; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EISCONN 106
static const int SHIM_FIX_EISCONN = 106; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTCONN 107
static const int SHIM_FIX_ENOTCONN = 107; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ESHUTDOWN 108
static const int SHIM_FIX_ESHUTDOWN = 108; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ETOOMANYREFS 109
static const int SHIM_FIX_ETOOMANYREFS = 109; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ETIMEDOUT 110
static const int SHIM_FIX_ETIMEDOUT = 110; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ETIME 62
static const int SHIM_FIX_ETIME = 62; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ECONNREFUSED 111
static const int SHIM_FIX_ECONNREFUSED = 111; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EHOSTDOWN 112
static const int SHIM_FIX_EHOSTDOWN = 112; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EHOSTUNREACH 113
static const int SHIM_FIX_EHOSTUNREACH = 113; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EALREADY 114
static const int SHIM_FIX_EALREADY = 114; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EINPROGRESS 115
static const int SHIM_FIX_EINPROGRESS = 115; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ESTALE 116
static const int SHIM_FIX_ESTALE = 116; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EDQUOT 122
static const int SHIM_FIX_EDQUOT = 122; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOMEDIUM 123
static const int SHIM_FIX_ENOMEDIUM = 123; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EMEDIUMTYPE 124
static const int SHIM_FIX_EMEDIUMTYPE = 124; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ECANCELED 125
static const int SHIM_FIX_ECANCELED = 125; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EOWNERDEAD 130
static const int SHIM_FIX_EOWNERDEAD = 130; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ENOTRECOVERABLE 131
static const int SHIM_FIX_ENOTRECOVERABLE = 131; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ERFKILL 132
static const int SHIM_FIX_ERFKILL = 132; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_EHWPOISON 133
static const int SHIM_FIX_EHWPOISON = 133; /* cosmo fixes this per-platform-invariant */
#define SHIM_ERRNO_TABLE(X) \
  X(SHIM_FIX_EPERM, SHIM_LIN_EPERM) \
  X(SHIM_FIX_ENOENT, SHIM_LIN_ENOENT) \
  X(SHIM_FIX_ESRCH, SHIM_LIN_ESRCH) \
  X(SHIM_FIX_EINTR, SHIM_LIN_EINTR) \
  X(SHIM_FIX_EIO, SHIM_LIN_EIO) \
  X(SHIM_FIX_ENXIO, SHIM_LIN_ENXIO) \
  X(SHIM_FIX_E2BIG, SHIM_LIN_E2BIG) \
  X(SHIM_FIX_ENOEXEC, SHIM_LIN_ENOEXEC) \
  X(SHIM_FIX_EBADF, SHIM_LIN_EBADF) \
  X(SHIM_FIX_ECHILD, SHIM_LIN_ECHILD) \
  X(SHIM_FIX_EAGAIN, SHIM_LIN_EAGAIN) \
  X(SHIM_FIX_ENOMEM, SHIM_LIN_ENOMEM) \
  X(SHIM_FIX_EACCES, SHIM_LIN_EACCES) \
  X(SHIM_FIX_EFAULT, SHIM_LIN_EFAULT) \
  X(SHIM_FIX_ENOTBLK, SHIM_LIN_ENOTBLK) \
  X(SHIM_FIX_EBUSY, SHIM_LIN_EBUSY) \
  X(SHIM_FIX_EEXIST, SHIM_LIN_EEXIST) \
  X(SHIM_FIX_EXDEV, SHIM_LIN_EXDEV) \
  X(SHIM_FIX_ENODEV, SHIM_LIN_ENODEV) \
  X(SHIM_FIX_ENOTDIR, SHIM_LIN_ENOTDIR) \
  X(SHIM_FIX_EISDIR, SHIM_LIN_EISDIR) \
  X(SHIM_FIX_EINVAL, SHIM_LIN_EINVAL) \
  X(SHIM_FIX_ENFILE, SHIM_LIN_ENFILE) \
  X(SHIM_FIX_EMFILE, SHIM_LIN_EMFILE) \
  X(SHIM_FIX_ENOTTY, SHIM_LIN_ENOTTY) \
  X(SHIM_FIX_ETXTBSY, SHIM_LIN_ETXTBSY) \
  X(SHIM_FIX_EFBIG, SHIM_LIN_EFBIG) \
  X(SHIM_FIX_ENOSPC, SHIM_LIN_ENOSPC) \
  X(SHIM_FIX_ESPIPE, SHIM_LIN_ESPIPE) \
  X(SHIM_FIX_EROFS, SHIM_LIN_EROFS) \
  X(SHIM_FIX_EMLINK, SHIM_LIN_EMLINK) \
  X(SHIM_FIX_EPIPE, SHIM_LIN_EPIPE) \
  X(SHIM_FIX_EDOM, SHIM_LIN_EDOM) \
  X(SHIM_FIX_ERANGE, SHIM_LIN_ERANGE) \
  X(SHIM_FIX_EDEADLK, SHIM_LIN_EDEADLK) \
  X(SHIM_FIX_ENAMETOOLONG, SHIM_LIN_ENAMETOOLONG) \
  X(SHIM_FIX_ENOLCK, SHIM_LIN_ENOLCK) \
  X(SHIM_FIX_ENOSYS, SHIM_LIN_ENOSYS) \
  X(SHIM_FIX_ENOTEMPTY, SHIM_LIN_ENOTEMPTY) \
  X(SHIM_FIX_ELOOP, SHIM_LIN_ELOOP) \
  X(SHIM_FIX_ENOMSG, SHIM_LIN_ENOMSG) \
  X(SHIM_FIX_EIDRM, SHIM_LIN_EIDRM) \
  X(SHIM_FIX_ENOSTR, SHIM_LIN_ENOSTR) \
  X(SHIM_FIX_ENODATA, SHIM_LIN_ENODATA) \
  X(SHIM_FIX_ENOSR, SHIM_LIN_ENOSR) \
  X(SHIM_FIX_ENONET, SHIM_LIN_ENONET) \
  X(SHIM_FIX_EREMOTE, SHIM_LIN_EREMOTE) \
  X(SHIM_FIX_ENOLINK, SHIM_LIN_ENOLINK) \
  X(SHIM_FIX_EPROTO, SHIM_LIN_EPROTO) \
  X(SHIM_FIX_EMULTIHOP, SHIM_LIN_EMULTIHOP) \
  X(SHIM_FIX_EBADMSG, SHIM_LIN_EBADMSG) \
  X(SHIM_FIX_EOVERFLOW, SHIM_LIN_EOVERFLOW) \
  X(SHIM_FIX_EBADFD, SHIM_LIN_EBADFD) \
  X(SHIM_FIX_EILSEQ, SHIM_LIN_EILSEQ) \
  X(SHIM_FIX_ERESTART, SHIM_LIN_ERESTART) \
  X(SHIM_FIX_EUSERS, SHIM_LIN_EUSERS) \
  X(SHIM_FIX_ENOTSOCK, SHIM_LIN_ENOTSOCK) \
  X(SHIM_FIX_EDESTADDRREQ, SHIM_LIN_EDESTADDRREQ) \
  X(SHIM_FIX_EMSGSIZE, SHIM_LIN_EMSGSIZE) \
  X(SHIM_FIX_EPROTOTYPE, SHIM_LIN_EPROTOTYPE) \
  X(SHIM_FIX_ENOPROTOOPT, SHIM_LIN_ENOPROTOOPT) \
  X(SHIM_FIX_EPROTONOSUPPORT, SHIM_LIN_EPROTONOSUPPORT) \
  X(SHIM_FIX_ESOCKTNOSUPPORT, SHIM_LIN_ESOCKTNOSUPPORT) \
  X(SHIM_FIX_EOPNOTSUPP, SHIM_LIN_EOPNOTSUPP) \
  X(SHIM_FIX_ENOTSUP, SHIM_LIN_ENOTSUP) \
  X(SHIM_FIX_EPFNOSUPPORT, SHIM_LIN_EPFNOSUPPORT) \
  X(SHIM_FIX_EAFNOSUPPORT, SHIM_LIN_EAFNOSUPPORT) \
  X(SHIM_FIX_EADDRINUSE, SHIM_LIN_EADDRINUSE) \
  X(SHIM_FIX_EADDRNOTAVAIL, SHIM_LIN_EADDRNOTAVAIL) \
  X(SHIM_FIX_ENETDOWN, SHIM_LIN_ENETDOWN) \
  X(SHIM_FIX_ENETUNREACH, SHIM_LIN_ENETUNREACH) \
  X(SHIM_FIX_ENETRESET, SHIM_LIN_ENETRESET) \
  X(SHIM_FIX_ECONNABORTED, SHIM_LIN_ECONNABORTED) \
  X(SHIM_FIX_ECONNRESET, SHIM_LIN_ECONNRESET) \
  X(SHIM_FIX_ENOBUFS, SHIM_LIN_ENOBUFS) \
  X(SHIM_FIX_EISCONN, SHIM_LIN_EISCONN) \
  X(SHIM_FIX_ENOTCONN, SHIM_LIN_ENOTCONN) \
  X(SHIM_FIX_ESHUTDOWN, SHIM_LIN_ESHUTDOWN) \
  X(SHIM_FIX_ETOOMANYREFS, SHIM_LIN_ETOOMANYREFS) \
  X(SHIM_FIX_ETIMEDOUT, SHIM_LIN_ETIMEDOUT) \
  X(SHIM_FIX_ETIME, SHIM_LIN_ETIME) \
  X(SHIM_FIX_ECONNREFUSED, SHIM_LIN_ECONNREFUSED) \
  X(SHIM_FIX_EHOSTDOWN, SHIM_LIN_EHOSTDOWN) \
  X(SHIM_FIX_EHOSTUNREACH, SHIM_LIN_EHOSTUNREACH) \
  X(SHIM_FIX_EALREADY, SHIM_LIN_EALREADY) \
  X(SHIM_FIX_EINPROGRESS, SHIM_LIN_EINPROGRESS) \
  X(SHIM_FIX_ESTALE, SHIM_LIN_ESTALE) \
  X(SHIM_FIX_EDQUOT, SHIM_LIN_EDQUOT) \
  X(SHIM_FIX_ENOMEDIUM, SHIM_LIN_ENOMEDIUM) \
  X(SHIM_FIX_EMEDIUMTYPE, SHIM_LIN_EMEDIUMTYPE) \
  X(SHIM_FIX_ECANCELED, SHIM_LIN_ECANCELED) \
  X(SHIM_FIX_EOWNERDEAD, SHIM_LIN_EOWNERDEAD) \
  X(SHIM_FIX_ENOTRECOVERABLE, SHIM_LIN_ENOTRECOVERABLE) \
  X(SHIM_FIX_ERFKILL, SHIM_LIN_ERFKILL) \
  X(SHIM_FIX_EHWPOISON, SHIM_LIN_EHWPOISON) \
  /* end SHIM_ERRNO_TABLE */

/* SHIM_OFLAG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/o.h */
#define SHIM_LIN_O_CREAT 64
static const unsigned SHIM_FIX_O_CREAT = 64; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_EXCL 128
static const unsigned SHIM_FIX_O_EXCL = 128; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_TRUNC 512
static const unsigned SHIM_FIX_O_TRUNC = 512; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_APPEND 1024
static const unsigned SHIM_FIX_O_APPEND = 1024; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_NONBLOCK 2048
static const unsigned SHIM_FIX_O_NONBLOCK = 2048; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_CLOEXEC 524288
static const unsigned SHIM_FIX_O_CLOEXEC = 524288; /* cosmo fixes this per-platform-invariant */
#if defined(__x86_64__)
#define SHIM_LIN_O_DIRECTORY 65536
#elif defined(__aarch64__)
#define SHIM_LIN_O_DIRECTORY 16384
#endif
static const unsigned SHIM_FIX_O_DIRECTORY = 65536; /* cosmo fixes this per-platform-invariant */
#if defined(__x86_64__)
#define SHIM_LIN_O_NOFOLLOW 131072
#elif defined(__aarch64__)
#define SHIM_LIN_O_NOFOLLOW 32768
#endif
static const unsigned SHIM_FIX_O_NOFOLLOW = 131072; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_PATH 2097152
static const unsigned SHIM_FIX__O_PATH = 2097152; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_DSYNC 4096
static const unsigned SHIM_FIX_O_DSYNC = 4096; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_NOCTTY 256
static const unsigned SHIM_FIX_O_NOCTTY = 256; /* cosmo fixes this per-platform-invariant */
#if defined(__x86_64__)
#define SHIM_LIN_O_DIRECT 16384
#elif defined(__aarch64__)
#define SHIM_LIN_O_DIRECT 65536
#endif
static const unsigned SHIM_FIX_O_DIRECT = 16384; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_O_NOATIME 262144
static const unsigned SHIM_FIX_O_NOATIME = 262144; /* cosmo fixes this per-platform-invariant */
#define SHIM_OFLAG_TABLE(X) \
  X(SHIM_FIX_O_CREAT, SHIM_LIN_O_CREAT, 0) \
  X(SHIM_FIX_O_EXCL, SHIM_LIN_O_EXCL, 0) \
  X(SHIM_FIX_O_TRUNC, SHIM_LIN_O_TRUNC, 0) \
  X(SHIM_FIX_O_APPEND, SHIM_LIN_O_APPEND, 0) \
  X(SHIM_FIX_O_NONBLOCK, SHIM_LIN_O_NONBLOCK, 0) \
  X(SHIM_FIX_O_CLOEXEC, SHIM_LIN_O_CLOEXEC, 0) \
  X(SHIM_FIX_O_DIRECTORY, SHIM_LIN_O_DIRECTORY, 0) \
  X(SHIM_FIX_O_NOFOLLOW, SHIM_LIN_O_NOFOLLOW, 0) \
  X(SHIM_FIX__O_PATH, SHIM_LIN_O_PATH, 1) \
  X(SHIM_FIX_O_DSYNC, SHIM_LIN_O_DSYNC, 0) \
  X(SHIM_FIX_O_NOCTTY, SHIM_LIN_O_NOCTTY, 1) \
  X(SHIM_FIX_O_DIRECT, SHIM_LIN_O_DIRECT, 1) \
  X(SHIM_FIX_O_NOATIME, SHIM_LIN_O_NOATIME, 1) \
  /* end SHIM_OFLAG_TABLE */

/* SHIM_FCNTL_CMD_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/f.h */
#define SHIM_LIN_F_GETLK 5
#define SHIM_LIN_F_SETLK 6
#define SHIM_LIN_F_SETLKW 7
#define SHIM_LIN_F_DUPFD_CLOEXEC 1030
static const int SHIM_FIX_F_DUPFD_CLOEXEC = 1030; /* cosmo fixes this per-platform-invariant */
#define SHIM_FCNTL_CMD_TABLE(X) \
  X(F_GETLK, SHIM_LIN_F_GETLK) \
  X(F_SETLK, SHIM_LIN_F_SETLK) \
  X(F_SETLKW, SHIM_LIN_F_SETLKW) \
  X(SHIM_FIX_F_DUPFD_CLOEXEC, SHIM_LIN_F_DUPFD_CLOEXEC) \
  /* end SHIM_FCNTL_CMD_TABLE */

/* SHIM_LOCKTYPE_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/f.h */
#define SHIM_LIN_F_RDLCK 0
#define SHIM_LIN_F_WRLCK 1
#define SHIM_LIN_F_UNLCK 2
static const int SHIM_FIX_F_UNLCK = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LOCKTYPE_TABLE(X) \
  X(F_RDLCK, SHIM_LIN_F_RDLCK) \
  X(F_WRLCK, SHIM_LIN_F_WRLCK) \
  X(SHIM_FIX_F_UNLCK, SHIM_LIN_F_UNLCK) \
  /* end SHIM_LOCKTYPE_TABLE */

/* SHIM_POLL_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/poll.h */
#define SHIM_LIN_POLLIN 1
#define SHIM_LIN_POLLPRI 2
#define SHIM_LIN_POLLOUT 4
#define SHIM_LIN_POLLERR 8
#define SHIM_LIN_POLLHUP 16
#define SHIM_LIN_POLLNVAL 32
#define SHIM_LIN_POLLRDNORM 64
#define SHIM_LIN_POLLRDBAND 128
#define SHIM_LIN_POLLWRNORM 256
#define SHIM_LIN_POLLWRBAND 512
#define SHIM_LIN_POLLRDHUP 8192
#define SHIM_POLL_TABLE(X) \
  X(POLLIN, SHIM_LIN_POLLIN) \
  X(POLLPRI, SHIM_LIN_POLLPRI) \
  X(POLLOUT, SHIM_LIN_POLLOUT) \
  X(POLLERR, SHIM_LIN_POLLERR) \
  X(POLLHUP, SHIM_LIN_POLLHUP) \
  X(POLLNVAL, SHIM_LIN_POLLNVAL) \
  X(POLLRDNORM, SHIM_LIN_POLLRDNORM) \
  X(POLLRDBAND, SHIM_LIN_POLLRDBAND) \
  X(POLLWRNORM, SHIM_LIN_POLLWRNORM) \
  X(POLLWRBAND, SHIM_LIN_POLLWRBAND) \
  X(POLLRDHUP, SHIM_LIN_POLLRDHUP) \
  /* end SHIM_POLL_TABLE */

/* SHIM_MSG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/msg.h */
#define SHIM_LIN_MSG_DONTWAIT 64
#define SHIM_LIN_MSG_WAITALL 256
#define SHIM_LIN_MSG_NOSIGNAL 16384
#define SHIM_LIN_MSG_TRUNC 32
#define SHIM_LIN_MSG_CTRUNC 8
#define SHIM_MSG_TABLE(X) \
  X(MSG_DONTWAIT, SHIM_LIN_MSG_DONTWAIT) \
  X(MSG_WAITALL, SHIM_LIN_MSG_WAITALL) \
  X(MSG_NOSIGNAL, SHIM_LIN_MSG_NOSIGNAL) \
  X(MSG_TRUNC, SHIM_LIN_MSG_TRUNC) \
  X(MSG_CTRUNC, SHIM_LIN_MSG_CTRUNC) \
  /* end SHIM_MSG_TABLE */

/* SHIM_SO_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/so.h */
#define SHIM_LIN_SO_REUSEADDR 2
#define SHIM_LIN_SO_TYPE 3
#define SHIM_LIN_SO_ERROR 4
#define SHIM_LIN_SO_DONTROUTE 5
#define SHIM_LIN_SO_BROADCAST 6
#define SHIM_LIN_SO_SNDBUF 7
#define SHIM_LIN_SO_RCVBUF 8
#define SHIM_LIN_SO_KEEPALIVE 9
#define SHIM_LIN_SO_OOBINLINE 10
#define SHIM_LIN_SO_LINGER 13
#define SHIM_LIN_SO_REUSEPORT 15
#define SHIM_LIN_SO_RCVLOWAT 18
#define SHIM_LIN_SO_SNDLOWAT 19
#define SHIM_LIN_SO_RCVTIMEO 20
#define SHIM_LIN_SO_SNDTIMEO 21
#define SHIM_LIN_SO_ACCEPTCONN 30
#define SHIM_SO_TABLE(X) \
  X(SO_REUSEADDR, SHIM_LIN_SO_REUSEADDR) \
  X(SO_TYPE, SHIM_LIN_SO_TYPE) \
  X(SO_ERROR, SHIM_LIN_SO_ERROR) \
  X(SO_DONTROUTE, SHIM_LIN_SO_DONTROUTE) \
  X(SO_BROADCAST, SHIM_LIN_SO_BROADCAST) \
  X(SO_SNDBUF, SHIM_LIN_SO_SNDBUF) \
  X(SO_RCVBUF, SHIM_LIN_SO_RCVBUF) \
  X(SO_KEEPALIVE, SHIM_LIN_SO_KEEPALIVE) \
  X(SO_OOBINLINE, SHIM_LIN_SO_OOBINLINE) \
  X(SO_LINGER, SHIM_LIN_SO_LINGER) \
  X(SO_REUSEPORT, SHIM_LIN_SO_REUSEPORT) \
  X(SO_RCVLOWAT, SHIM_LIN_SO_RCVLOWAT) \
  X(SO_SNDLOWAT, SHIM_LIN_SO_SNDLOWAT) \
  X(SO_RCVTIMEO, SHIM_LIN_SO_RCVTIMEO) \
  X(SO_SNDTIMEO, SHIM_LIN_SO_SNDTIMEO) \
  X(SO_ACCEPTCONN, SHIM_LIN_SO_ACCEPTCONN) \
  /* end SHIM_SO_TABLE */

/* SHIM_TCP_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/tcp.h */
#define SHIM_LIN_TCP_NODELAY 1
static const int SHIM_FIX_TCP_NODELAY = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_TCP_MAXSEG 2
#define SHIM_LIN_TCP_CORK 3
#define SHIM_LIN_TCP_KEEPIDLE 4
#define SHIM_LIN_TCP_KEEPINTVL 5
#define SHIM_LIN_TCP_KEEPCNT 6
#define SHIM_LIN_TCP_SYNCNT 7
#define SHIM_LIN_TCP_DEFER_ACCEPT 9
#define SHIM_LIN_TCP_FASTOPEN 23
#define SHIM_LIN_TCP_QUICKACK 12
#define SHIM_TCP_TABLE(X) \
  X(SHIM_FIX_TCP_NODELAY, SHIM_LIN_TCP_NODELAY) \
  X(TCP_MAXSEG, SHIM_LIN_TCP_MAXSEG) \
  X(TCP_CORK, SHIM_LIN_TCP_CORK) \
  X(TCP_KEEPIDLE, SHIM_LIN_TCP_KEEPIDLE) \
  X(TCP_KEEPINTVL, SHIM_LIN_TCP_KEEPINTVL) \
  X(TCP_KEEPCNT, SHIM_LIN_TCP_KEEPCNT) \
  X(TCP_SYNCNT, SHIM_LIN_TCP_SYNCNT) \
  X(TCP_DEFER_ACCEPT, SHIM_LIN_TCP_DEFER_ACCEPT) \
  X(TCP_FASTOPEN, SHIM_LIN_TCP_FASTOPEN) \
  X(TCP_QUICKACK, SHIM_LIN_TCP_QUICKACK) \
  /* end SHIM_TCP_TABLE */

/* SHIM_IP_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/ip.h */
#define SHIM_LIN_IP_TOS 1
#define SHIM_LIN_IP_TTL 2
#define SHIM_LIN_IP_HDRINCL 3
#define SHIM_LIN_IP_OPTIONS 4
#define SHIM_LIN_IP_RECVTOS 13
#define SHIM_LIN_IP_RECVTTL 12
#define SHIM_LIN_IP_MULTICAST_IF 32
#define SHIM_LIN_IP_MULTICAST_TTL 33
#define SHIM_LIN_IP_MULTICAST_LOOP 34
#define SHIM_LIN_IP_ADD_MEMBERSHIP 35
#define SHIM_LIN_IP_DROP_MEMBERSHIP 36
#define SHIM_LIN_IP_PKTINFO 8
#define SHIM_IP_TABLE(X) \
  X(IP_TOS, SHIM_LIN_IP_TOS) \
  X(IP_TTL, SHIM_LIN_IP_TTL) \
  X(IP_HDRINCL, SHIM_LIN_IP_HDRINCL) \
  X(IP_OPTIONS, SHIM_LIN_IP_OPTIONS) \
  X(IP_RECVTOS, SHIM_LIN_IP_RECVTOS) \
  X(IP_RECVTTL, SHIM_LIN_IP_RECVTTL) \
  X(IP_MULTICAST_IF, SHIM_LIN_IP_MULTICAST_IF) \
  X(IP_MULTICAST_TTL, SHIM_LIN_IP_MULTICAST_TTL) \
  X(IP_MULTICAST_LOOP, SHIM_LIN_IP_MULTICAST_LOOP) \
  X(IP_ADD_MEMBERSHIP, SHIM_LIN_IP_ADD_MEMBERSHIP) \
  X(IP_DROP_MEMBERSHIP, SHIM_LIN_IP_DROP_MEMBERSHIP) \
  X(IP_PKTINFO, SHIM_LIN_IP_PKTINFO) \
  /* end SHIM_IP_TABLE */

/* SHIM_IPV6_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/ipv6.h */
#define SHIM_LIN_IPV6_V6ONLY 26
#define SHIM_LIN_IPV6_UNICAST_HOPS 16
#define SHIM_LIN_IPV6_MULTICAST_IF 17
#define SHIM_LIN_IPV6_MULTICAST_HOPS 18
#define SHIM_LIN_IPV6_MULTICAST_LOOP 19
#define SHIM_LIN_IPV6_ADD_MEMBERSHIP 20
#define SHIM_LIN_IPV6_DROP_MEMBERSHIP 21
#define SHIM_LIN_IPV6_TCLASS 67
#define SHIM_LIN_IPV6_RECVTCLASS 66
#define SHIM_LIN_IPV6_PKTINFO 50
#define SHIM_IPV6_TABLE(X) \
  X(IPV6_V6ONLY, SHIM_LIN_IPV6_V6ONLY) \
  X(IPV6_UNICAST_HOPS, SHIM_LIN_IPV6_UNICAST_HOPS) \
  X(IPV6_MULTICAST_IF, SHIM_LIN_IPV6_MULTICAST_IF) \
  X(IPV6_MULTICAST_HOPS, SHIM_LIN_IPV6_MULTICAST_HOPS) \
  X(IPV6_MULTICAST_LOOP, SHIM_LIN_IPV6_MULTICAST_LOOP) \
  X(IPV6_JOIN_GROUP, SHIM_LIN_IPV6_ADD_MEMBERSHIP) \
  X(IPV6_LEAVE_GROUP, SHIM_LIN_IPV6_DROP_MEMBERSHIP) \
  X(IPV6_TCLASS, SHIM_LIN_IPV6_TCLASS) \
  X(IPV6_RECVTCLASS, SHIM_LIN_IPV6_RECVTCLASS) \
  X(IPV6_PKTINFO, SHIM_LIN_IPV6_PKTINFO) \
  /* end SHIM_IPV6_TABLE */

/* SHIM_MAP_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/map.h */
#define SHIM_LIN_MAP_ANONYMOUS 32
#define SHIM_LIN_MAP_FIXED_NOREPLACE 1048576
#define SHIM_LIN_MAP_HUGETLB 262144
#define SHIM_LIN_MAP_NORESERVE 16384
#define SHIM_LIN_MAP_POPULATE 32768
#define SHIM_LIN_MAP_LOCKED 8192
#define SHIM_MAP_TABLE(X) \
  X(MAP_ANONYMOUS, SHIM_LIN_MAP_ANONYMOUS, 0) \
  X(MAP_FIXED_NOREPLACE, SHIM_LIN_MAP_FIXED_NOREPLACE, 0) \
  X(MAP_HUGETLB, SHIM_LIN_MAP_HUGETLB, 0) \
  X(MAP_NORESERVE, SHIM_LIN_MAP_NORESERVE, 1) \
  X(MAP_POPULATE, SHIM_LIN_MAP_POPULATE, 1) \
  X(MAP_LOCKED, SHIM_LIN_MAP_LOCKED, 1) \
  /* end SHIM_MAP_TABLE */

/* SHIM_CLOCK_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/clock.h */
#define SHIM_LIN_CLOCK_REALTIME 0
static const int SHIM_FIX_CLOCK_REALTIME = 0; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_CLOCK_MONOTONIC 1
#define SHIM_LIN_CLOCK_PROCESS_CPUTIME_ID 2
#define SHIM_LIN_CLOCK_THREAD_CPUTIME_ID 3
#define SHIM_LIN_CLOCK_MONOTONIC_RAW 4
#define SHIM_LIN_CLOCK_REALTIME_COARSE 5
#define SHIM_LIN_CLOCK_MONOTONIC_COARSE 6
#define SHIM_LIN_CLOCK_BOOTTIME 7
#define SHIM_CLOCK_TABLE(X) \
  X(SHIM_FIX_CLOCK_REALTIME, SHIM_LIN_CLOCK_REALTIME) \
  X(CLOCK_MONOTONIC, SHIM_LIN_CLOCK_MONOTONIC) \
  X(CLOCK_PROCESS_CPUTIME_ID, SHIM_LIN_CLOCK_PROCESS_CPUTIME_ID) \
  X(CLOCK_THREAD_CPUTIME_ID, SHIM_LIN_CLOCK_THREAD_CPUTIME_ID) \
  X(CLOCK_MONOTONIC_RAW, SHIM_LIN_CLOCK_MONOTONIC_RAW) \
  X(CLOCK_REALTIME_COARSE, SHIM_LIN_CLOCK_REALTIME_COARSE) \
  X(CLOCK_MONOTONIC_COARSE, SHIM_LIN_CLOCK_MONOTONIC_COARSE) \
  X(CLOCK_BOOTTIME, SHIM_LIN_CLOCK_BOOTTIME) \
  /* end SHIM_CLOCK_TABLE */

/* SHIM_MADV_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/madv.h */
#define SHIM_LIN_MADV_NORMAL 0
static const unsigned SHIM_FIX_MADV_NORMAL = 0; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_MADV_RANDOM 1
static const unsigned SHIM_FIX_MADV_RANDOM = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_MADV_SEQUENTIAL 2
static const unsigned SHIM_FIX_MADV_SEQUENTIAL = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_MADV_WILLNEED 3
static const unsigned SHIM_FIX_MADV_WILLNEED = 3; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_MADV_DONTNEED 4
static const unsigned SHIM_FIX_MADV_DONTNEED = 4; /* cosmo fixes this per-platform-invariant */
#define SHIM_MADV_TABLE(X) \
  X(SHIM_FIX_MADV_NORMAL, SHIM_LIN_MADV_NORMAL) \
  X(SHIM_FIX_MADV_RANDOM, SHIM_LIN_MADV_RANDOM) \
  X(SHIM_FIX_MADV_SEQUENTIAL, SHIM_LIN_MADV_SEQUENTIAL) \
  X(SHIM_FIX_MADV_WILLNEED, SHIM_LIN_MADV_WILLNEED) \
  X(SHIM_FIX_MADV_DONTNEED, SHIM_LIN_MADV_DONTNEED) \
  /* end SHIM_MADV_TABLE */

/* SHIM_RLIMIT_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/rlimit.h */
#define SHIM_LIN_RLIMIT_CPU 0
static const unsigned SHIM_FIX_RLIMIT_CPU = 0; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_FSIZE 1
static const unsigned SHIM_FIX_RLIMIT_FSIZE = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_DATA 2
static const unsigned SHIM_FIX_RLIMIT_DATA = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_STACK 3
static const unsigned SHIM_FIX_RLIMIT_STACK = 3; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_CORE 4
static const unsigned SHIM_FIX_RLIMIT_CORE = 4; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_RSS 5
static const unsigned SHIM_FIX_RLIMIT_RSS = 5; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_NPROC 6
static const unsigned SHIM_FIX_RLIMIT_NPROC = 6; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_NOFILE 7
static const unsigned SHIM_FIX_RLIMIT_NOFILE = 7; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_MEMLOCK 8
static const unsigned SHIM_FIX_RLIMIT_MEMLOCK = 8; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_RLIMIT_AS 9
static const unsigned SHIM_FIX_RLIMIT_AS = 9; /* cosmo fixes this per-platform-invariant */
#define SHIM_RLIMIT_TABLE(X) \
  X(SHIM_FIX_RLIMIT_CPU, SHIM_LIN_RLIMIT_CPU) \
  X(SHIM_FIX_RLIMIT_FSIZE, SHIM_LIN_RLIMIT_FSIZE) \
  X(SHIM_FIX_RLIMIT_DATA, SHIM_LIN_RLIMIT_DATA) \
  X(SHIM_FIX_RLIMIT_STACK, SHIM_LIN_RLIMIT_STACK) \
  X(SHIM_FIX_RLIMIT_CORE, SHIM_LIN_RLIMIT_CORE) \
  X(SHIM_FIX_RLIMIT_RSS, SHIM_LIN_RLIMIT_RSS) \
  X(SHIM_FIX_RLIMIT_NPROC, SHIM_LIN_RLIMIT_NPROC) \
  X(SHIM_FIX_RLIMIT_NOFILE, SHIM_LIN_RLIMIT_NOFILE) \
  X(SHIM_FIX_RLIMIT_MEMLOCK, SHIM_LIN_RLIMIT_MEMLOCK) \
  X(SHIM_FIX_RLIMIT_AS, SHIM_LIN_RLIMIT_AS) \
  /* end SHIM_RLIMIT_TABLE */

/* SHIM_SIG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/sig.h */
#define SHIM_LIN_SIGBUS 7
static const int SHIM_FIX_SIGBUS = 7; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGUSR1 10
static const int SHIM_FIX_SIGUSR1 = 10; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGUSR2 12
static const int SHIM_FIX_SIGUSR2 = 12; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGCHLD 17
static const int SHIM_FIX_SIGCHLD = 17; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGCONT 18
static const int SHIM_FIX_SIGCONT = 18; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGSTOP 19
static const int SHIM_FIX_SIGSTOP = 19; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGTSTP 20
static const int SHIM_FIX_SIGTSTP = 20; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGURG 23
static const int SHIM_FIX_SIGURG = 23; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SIGSYS 31
static const int SHIM_FIX_SIGSYS = 31; /* cosmo fixes this per-platform-invariant */
#define SHIM_SIG_TABLE(X) \
  X(SHIM_FIX_SIGBUS, SHIM_LIN_SIGBUS) \
  X(SHIM_FIX_SIGUSR1, SHIM_LIN_SIGUSR1) \
  X(SHIM_FIX_SIGUSR2, SHIM_LIN_SIGUSR2) \
  X(SHIM_FIX_SIGCHLD, SHIM_LIN_SIGCHLD) \
  X(SHIM_FIX_SIGCONT, SHIM_LIN_SIGCONT) \
  X(SHIM_FIX_SIGSTOP, SHIM_LIN_SIGSTOP) \
  X(SHIM_FIX_SIGTSTP, SHIM_LIN_SIGTSTP) \
  X(SHIM_FIX_SIGURG, SHIM_LIN_SIGURG) \
  X(SHIM_FIX_SIGSYS, SHIM_LIN_SIGSYS) \
  /* end SHIM_SIG_TABLE */

/* SHIM_SA_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/sa.h */
#define SHIM_LIN_SA_NOCLDSTOP 1
#define SHIM_LIN_SA_NOCLDWAIT 2
#define SHIM_LIN_SA_SIGINFO 4
#define SHIM_LIN_SA_ONSTACK 134217728
#define SHIM_LIN_SA_RESTART 268435456
#define SHIM_LIN_SA_NODEFER 1073741824
#define SHIM_LIN_SA_RESETHAND -2147483648
#define SHIM_SA_TABLE(X) \
  X(SA_NOCLDSTOP, SHIM_LIN_SA_NOCLDSTOP) \
  X(SA_NOCLDWAIT, SHIM_LIN_SA_NOCLDWAIT) \
  X(SA_SIGINFO, SHIM_LIN_SA_SIGINFO) \
  X(SA_ONSTACK, SHIM_LIN_SA_ONSTACK) \
  X(SA_RESTART, SHIM_LIN_SA_RESTART) \
  X(SA_NODEFER, SHIM_LIN_SA_NODEFER) \
  X(SA_RESETHAND, SHIM_LIN_SA_RESETHAND) \
  /* end SHIM_SA_TABLE */

/* SHIM_SS_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/ss.h */
#define SHIM_LIN_SS_ONSTACK 1
static const int SHIM_FIX_SS_ONSTACK = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_SS_DISABLE 2
#define SHIM_SS_TABLE(X) \
  X(SHIM_FIX_SS_ONSTACK, SHIM_LIN_SS_ONSTACK) \
  X(SS_DISABLE, SHIM_LIN_SS_DISABLE) \
  /* end SHIM_SS_TABLE */

/* SHIM_AUXV_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/auxv.h */
#define SHIM_LIN_AT_MINSIGSTKSZ 51
#define SHIM_LIN_AT_HWCAP 16
#define SHIM_LIN_AT_HWCAP2 26
#define SHIM_AUXV_TABLE(X) \
  X(AT_MINSIGSTKSZ, SHIM_LIN_AT_MINSIGSTKSZ) \
  X(AT_HWCAP, SHIM_LIN_AT_HWCAP) \
  X(AT_HWCAP2, SHIM_LIN_AT_HWCAP2) \
  /* end SHIM_AUXV_TABLE */

/* SHIM_AF_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/af.h */
#define SHIM_LIN_AF_UNSPEC 0
static const int SHIM_FIX_AF_UNSPEC = 0; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_AF_UNIX 1
static const int SHIM_FIX_AF_UNIX = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_AF_INET 2
static const int SHIM_FIX_AF_INET = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_AF_INET6 10
#define SHIM_AF_TABLE(X) \
  X(SHIM_FIX_AF_UNSPEC, SHIM_LIN_AF_UNSPEC) \
  X(SHIM_FIX_AF_UNIX, SHIM_LIN_AF_UNIX) \
  X(SHIM_FIX_AF_INET, SHIM_LIN_AF_INET) \
  X(AF_INET6, SHIM_LIN_AF_INET6) \
  /* end SHIM_AF_TABLE */

/* SHIM_TIFLAG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_IGNBRK 1
static const uint32_t SHIM_FIX_IGNBRK = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_BRKINT 2
static const uint32_t SHIM_FIX_BRKINT = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_IGNPAR 4
static const uint32_t SHIM_FIX_IGNPAR = 4; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_PARMRK 8
static const uint32_t SHIM_FIX_PARMRK = 8; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_INPCK 16
static const uint32_t SHIM_FIX_INPCK = 16; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ISTRIP 32
static const uint32_t SHIM_FIX_ISTRIP = 32; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_INLCR 64
static const uint32_t SHIM_FIX_INLCR = 64; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_IGNCR 128
static const uint32_t SHIM_FIX_IGNCR = 128; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ICRNL 256
static const uint32_t SHIM_FIX_ICRNL = 256; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_IUCLC 512
#define SHIM_LIN_IXON 1024
#define SHIM_LIN_IXANY 2048
static const uint32_t SHIM_FIX_IXANY = 2048; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_IXOFF 4096
#define SHIM_LIN_IMAXBEL 8192
static const uint32_t SHIM_FIX_IMAXBEL = 8192; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_IUTF8 16384
#define SHIM_TIFLAG_TABLE(X) \
  X(SHIM_FIX_IGNBRK, SHIM_LIN_IGNBRK) \
  X(SHIM_FIX_BRKINT, SHIM_LIN_BRKINT) \
  X(SHIM_FIX_IGNPAR, SHIM_LIN_IGNPAR) \
  X(SHIM_FIX_PARMRK, SHIM_LIN_PARMRK) \
  X(SHIM_FIX_INPCK, SHIM_LIN_INPCK) \
  X(SHIM_FIX_ISTRIP, SHIM_LIN_ISTRIP) \
  X(SHIM_FIX_INLCR, SHIM_LIN_INLCR) \
  X(SHIM_FIX_IGNCR, SHIM_LIN_IGNCR) \
  X(SHIM_FIX_ICRNL, SHIM_LIN_ICRNL) \
  X(IUCLC, SHIM_LIN_IUCLC) \
  X(IXON, SHIM_LIN_IXON) \
  X(SHIM_FIX_IXANY, SHIM_LIN_IXANY) \
  X(IXOFF, SHIM_LIN_IXOFF) \
  X(SHIM_FIX_IMAXBEL, SHIM_LIN_IMAXBEL) \
  X(IUTF8, SHIM_LIN_IUTF8) \
  /* end SHIM_TIFLAG_TABLE */

/* SHIM_TOFLAG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_OPOST 1
static const uint32_t SHIM_FIX_OPOST = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_OLCUC 2
#define SHIM_LIN_ONLCR 4
#define SHIM_LIN_OCRNL 8
#define SHIM_LIN_ONOCR 16
#define SHIM_LIN_ONLRET 32
#define SHIM_LIN_OFILL 64
#define SHIM_LIN_OFDEL 128
#define SHIM_TOFLAG_TABLE(X) \
  X(SHIM_FIX_OPOST, SHIM_LIN_OPOST) \
  X(OLCUC, SHIM_LIN_OLCUC) \
  X(ONLCR, SHIM_LIN_ONLCR) \
  X(OCRNL, SHIM_LIN_OCRNL) \
  X(ONOCR, SHIM_LIN_ONOCR) \
  X(ONLRET, SHIM_LIN_ONLRET) \
  X(OFILL, SHIM_LIN_OFILL) \
  X(OFDEL, SHIM_LIN_OFDEL) \
  /* end SHIM_TOFLAG_TABLE */

/* SHIM_TODLY_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_NLDLY 256
#define SHIM_LIN_NL1 256
#define SHIM_LIN_CRDLY 1536
#define SHIM_LIN_CR1 512
#define SHIM_LIN_CR2 1024
#define SHIM_LIN_CR3 1536
#define SHIM_LIN_TABDLY 6144
#define SHIM_LIN_TAB1 2048
#define SHIM_LIN_TAB2 4096
#define SHIM_LIN_TAB3 6144
#define SHIM_LIN_XTABS 6144
#define SHIM_LIN_BSDLY 8192
#define SHIM_LIN_BS1 8192
#define SHIM_LIN_VTDLY 16384
#define SHIM_LIN_VT1 16384
#define SHIM_LIN_FFDLY 32768
#define SHIM_LIN_FF1 32768
#define SHIM_TODLY_TABLE(X) \
  X(NLDLY, SHIM_LIN_NLDLY) \
  X(NL1, SHIM_LIN_NL1) \
  X(CRDLY, SHIM_LIN_CRDLY) \
  X(CR1, SHIM_LIN_CR1) \
  X(CR2, SHIM_LIN_CR2) \
  X(CR3, SHIM_LIN_CR3) \
  X(TABDLY, SHIM_LIN_TABDLY) \
  X(TAB1, SHIM_LIN_TAB1) \
  X(TAB2, SHIM_LIN_TAB2) \
  X(TAB3, SHIM_LIN_TAB3) \
  X(XTABS, SHIM_LIN_XTABS) \
  X(BSDLY, SHIM_LIN_BSDLY) \
  X(BS1, SHIM_LIN_BS1) \
  X(VTDLY, SHIM_LIN_VTDLY) \
  X(VT1, SHIM_LIN_VT1) \
  X(FFDLY, SHIM_LIN_FFDLY) \
  X(FF1, SHIM_LIN_FF1) \
  /* end SHIM_TODLY_TABLE */

/* SHIM_TCFLAG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_CSIZE 48
#define SHIM_LIN_CS6 16
#define SHIM_LIN_CS7 32
#define SHIM_LIN_CS8 48
#define SHIM_LIN_CSTOPB 64
#define SHIM_LIN_CREAD 128
#define SHIM_LIN_PARENB 256
#define SHIM_LIN_PARODD 512
#define SHIM_LIN_HUPCL 1024
#define SHIM_LIN_CLOCAL 2048
#define SHIM_LIN_CRTSCTS 2147483648
#define SHIM_LIN_CMSPAR 1073741824
#define SHIM_TCFLAG_TABLE(X) \
  X(CSIZE, SHIM_LIN_CSIZE) \
  X(CS6, SHIM_LIN_CS6) \
  X(CS7, SHIM_LIN_CS7) \
  X(CS8, SHIM_LIN_CS8) \
  X(CSTOPB, SHIM_LIN_CSTOPB) \
  X(CREAD, SHIM_LIN_CREAD) \
  X(PARENB, SHIM_LIN_PARENB) \
  X(PARODD, SHIM_LIN_PARODD) \
  X(HUPCL, SHIM_LIN_HUPCL) \
  X(CLOCAL, SHIM_LIN_CLOCAL) \
  X(CRTSCTS, SHIM_LIN_CRTSCTS) \
  X(CMSPAR, SHIM_LIN_CMSPAR) \
  /* end SHIM_TCFLAG_TABLE */

/* SHIM_TLFLAG_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_ISIG 1
#define SHIM_LIN_ICANON 2
#define SHIM_LIN_XCASE 4
#define SHIM_LIN_ECHO 8
static const uint32_t SHIM_FIX_ECHO = 8; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_ECHOE 16
#define SHIM_LIN_ECHOK 32
#define SHIM_LIN_ECHONL 64
#define SHIM_LIN_NOFLSH 128
#define SHIM_LIN_TOSTOP 256
#define SHIM_LIN_ECHOCTL 512
#define SHIM_LIN_ECHOPRT 1024
#define SHIM_LIN_ECHOKE 2048
#define SHIM_LIN_FLUSHO 4096
#define SHIM_LIN_PENDIN 16384
#define SHIM_LIN_IEXTEN 32768
#define SHIM_LIN_EXTPROC 65536
#define SHIM_TLFLAG_TABLE(X) \
  X(ISIG, SHIM_LIN_ISIG) \
  X(ICANON, SHIM_LIN_ICANON) \
  X(XCASE, SHIM_LIN_XCASE) \
  X(SHIM_FIX_ECHO, SHIM_LIN_ECHO) \
  X(ECHOE, SHIM_LIN_ECHOE) \
  X(ECHOK, SHIM_LIN_ECHOK) \
  X(ECHONL, SHIM_LIN_ECHONL) \
  X(NOFLSH, SHIM_LIN_NOFLSH) \
  X(TOSTOP, SHIM_LIN_TOSTOP) \
  X(ECHOCTL, SHIM_LIN_ECHOCTL) \
  X(ECHOPRT, SHIM_LIN_ECHOPRT) \
  X(ECHOKE, SHIM_LIN_ECHOKE) \
  X(FLUSHO, SHIM_LIN_FLUSHO) \
  X(PENDIN, SHIM_LIN_PENDIN) \
  X(IEXTEN, SHIM_LIN_IEXTEN) \
  X(EXTPROC, SHIM_LIN_EXTPROC) \
  /* end SHIM_TLFLAG_TABLE */

/* SHIM_TCC_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_VINTR 0
#define SHIM_LIN_VQUIT 1
#define SHIM_LIN_VERASE 2
#define SHIM_LIN_VKILL 3
#define SHIM_LIN_VEOF 4
#define SHIM_LIN_VTIME 5
#define SHIM_LIN_VMIN 6
#define SHIM_LIN_VSWTC 7
#define SHIM_LIN_VSTART 8
#define SHIM_LIN_VSTOP 9
#define SHIM_LIN_VSUSP 10
#define SHIM_LIN_VEOL 11
#define SHIM_LIN_VREPRINT 12
#define SHIM_LIN_VDISCARD 13
#define SHIM_LIN_VWERASE 14
#define SHIM_LIN_VLNEXT 15
#define SHIM_LIN_VEOL2 16
#define SHIM_TCC_TABLE(X) \
  X(VINTR, SHIM_LIN_VINTR) \
  X(VQUIT, SHIM_LIN_VQUIT) \
  X(VERASE, SHIM_LIN_VERASE) \
  X(VKILL, SHIM_LIN_VKILL) \
  X(VEOF, SHIM_LIN_VEOF) \
  X(VTIME, SHIM_LIN_VTIME) \
  X(VMIN, SHIM_LIN_VMIN) \
  X(VSWTC, SHIM_LIN_VSWTC) \
  X(VSTART, SHIM_LIN_VSTART) \
  X(VSTOP, SHIM_LIN_VSTOP) \
  X(VSUSP, SHIM_LIN_VSUSP) \
  X(VEOL, SHIM_LIN_VEOL) \
  X(VREPRINT, SHIM_LIN_VREPRINT) \
  X(VDISCARD, SHIM_LIN_VDISCARD) \
  X(VWERASE, SHIM_LIN_VWERASE) \
  X(VLNEXT, SHIM_LIN_VLNEXT) \
  X(VEOL2, SHIM_LIN_VEOL2) \
  /* end SHIM_TCC_TABLE */

/* SHIM_BAUD_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/baud.internal.h */
#define SHIM_LIN_B0 0
static const uint32_t SHIM_FIX_B0 = 0; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_B50 1
#define SHIM_LIN_B75 2
#define SHIM_LIN_B110 3
#define SHIM_LIN_B134 4
#define SHIM_LIN_B150 5
#define SHIM_LIN_B200 6
#define SHIM_LIN_B300 7
#define SHIM_LIN_B600 8
#define SHIM_LIN_B1200 9
#define SHIM_LIN_B1800 10
#define SHIM_LIN_B2400 11
#define SHIM_LIN_B4800 12
#define SHIM_LIN_B9600 13
#define SHIM_LIN_B19200 14
#define SHIM_LIN_B38400 15
#define SHIM_LIN_B57600 4097
#define SHIM_LIN_B115200 4098
#define SHIM_LIN_B230400 4099
#define SHIM_LIN_B500000 4101
#define SHIM_LIN_B576000 4102
#define SHIM_LIN_B1000000 4104
#define SHIM_LIN_B1152000 4105
#define SHIM_LIN_B1500000 4106
#define SHIM_LIN_B2000000 4107
#define SHIM_LIN_B2500000 4108
#define SHIM_LIN_B3000000 4109
#define SHIM_LIN_B3500000 4110
#define SHIM_LIN_B4000000 4111
#define SHIM_BAUD_TABLE(X) \
  X(SHIM_FIX_B0, SHIM_LIN_B0) \
  X(B50, SHIM_LIN_B50) \
  X(B75, SHIM_LIN_B75) \
  X(B110, SHIM_LIN_B110) \
  X(B134, SHIM_LIN_B134) \
  X(B150, SHIM_LIN_B150) \
  X(B200, SHIM_LIN_B200) \
  X(B300, SHIM_LIN_B300) \
  X(B600, SHIM_LIN_B600) \
  X(B1200, SHIM_LIN_B1200) \
  X(B1800, SHIM_LIN_B1800) \
  X(B2400, SHIM_LIN_B2400) \
  X(B4800, SHIM_LIN_B4800) \
  X(B9600, SHIM_LIN_B9600) \
  X(B19200, SHIM_LIN_B19200) \
  X(B38400, SHIM_LIN_B38400) \
  X(B57600, SHIM_LIN_B57600) \
  X(B115200, SHIM_LIN_B115200) \
  X(B230400, SHIM_LIN_B230400) \
  X(B500000, SHIM_LIN_B500000) \
  X(B576000, SHIM_LIN_B576000) \
  X(B1000000, SHIM_LIN_B1000000) \
  X(B1152000, SHIM_LIN_B1152000) \
  X(B1500000, SHIM_LIN_B1500000) \
  X(B2000000, SHIM_LIN_B2000000) \
  X(B2500000, SHIM_LIN_B2500000) \
  X(B3000000, SHIM_LIN_B3000000) \
  X(B3500000, SHIM_LIN_B3500000) \
  X(B4000000, SHIM_LIN_B4000000) \
  /* end SHIM_BAUD_TABLE */

/* SHIM_TCFLUSH_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_TCIFLUSH 0
#define SHIM_LIN_TCOFLUSH 1
#define SHIM_LIN_TCIOFLUSH 2
#define SHIM_TCFLUSH_TABLE(X) \
  X(TCIFLUSH, SHIM_LIN_TCIFLUSH) \
  X(TCOFLUSH, SHIM_LIN_TCOFLUSH) \
  X(TCIOFLUSH, SHIM_LIN_TCIOFLUSH) \
  /* end SHIM_TCFLUSH_TABLE */

/* SHIM_TCFLOW_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_TCOOFF 0
static const int SHIM_FIX_TCOOFF = 0; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_TCOON 1
static const int SHIM_FIX_TCOON = 1; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_TCIOFF 2
static const int SHIM_FIX_TCIOFF = 2; /* cosmo fixes this per-platform-invariant */
#define SHIM_LIN_TCION 3
static const int SHIM_FIX_TCION = 3; /* cosmo fixes this per-platform-invariant */
#define SHIM_TCFLOW_TABLE(X) \
  X(SHIM_FIX_TCOOFF, SHIM_LIN_TCOOFF) \
  X(SHIM_FIX_TCOON, SHIM_LIN_TCOON) \
  X(SHIM_FIX_TCIOFF, SHIM_LIN_TCIOFF) \
  X(SHIM_FIX_TCION, SHIM_LIN_TCION) \
  /* end SHIM_TCFLOW_TABLE */

/* SHIM_TIOC_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/termios.h */
#define SHIM_LIN_TIOCGWINSZ 21523
#define SHIM_LIN_TIOCSWINSZ 21524
#define SHIM_LIN_TIOCSCTTY 21518
#define SHIM_LIN_TIOCNOTTY 21538
#define SHIM_TIOC_TABLE(X) \
  X(TIOCGWINSZ, SHIM_LIN_TIOCGWINSZ) \
  X(TIOCSWINSZ, SHIM_LIN_TIOCSWINSZ) \
  X(TIOCSCTTY, SHIM_LIN_TIOCSCTTY) \
  X(TIOCNOTTY, SHIM_LIN_TIOCNOTTY) \
  /* end SHIM_TIOC_TABLE */

/* SHIM_FIO_TABLE <- libc crate; cosmo side declared in libc/sysv/consts/fio.h */
#define SHIM_LIN_FIONREAD 21531
#define SHIM_FIO_TABLE(X) \
  X(FIONREAD, SHIM_LIN_FIONREAD) \
  /* end SHIM_FIO_TABLE */

#endif /* RUST_APE_SHIM_TABLES_H_ */
